# Промисы.

- ***Промисы позволяют обрабатывать `отложенные` во времени события.***
- ***Промис - это обещание предоставить результат позже.***
- ***Промис может вернуть ошибку если результат предоставить невозможно.***

### У промиса может быть 3 состояния:

1. Ожидание.
2. Исполнен.
3. Отклонен.

## Создание промиса.

```javascript
const myPromise = new Promise((resolve, reject) => {
    /*
    Вновь созданный промис будет в состоянии pending.
    Выполнение асинхронных действий.
    Внутри этой функции нужно в результате вызвать одну из функций resolve или reject.
     */
})
```

### Получение результата промиса.

```javascript
myPromise
    .then(value => {
        /*
        Действия в случае успешного исполнения Промиса.
        Значение value - это значение, переданное в вызове функции resolve внутри Промиса.
         */
    })
    .catch(error => {
        /*
        Действия в случае отклонения Промиса.
        Значение error - это значение, переданное в вызове функции reject внутри Промиса.
         */
    })
```

## Получение данных с помощью fetch api.

```javascript
fetch('https://jsonplaceholder.typicode.com/todos')
    .then(response => response.json()) // Метод json возвращает Промис.
    .then(json => console.log(json)) // Поэтому второй раз вызываем метод then (т.к. fetch и json возвращают Промис.).
    .catch(error => console.log(error))
```

#### Выполнить в консоле браузере на сайте jsonplaceholder.
```javascript
fetch('https://jsonplaceholder.typicode.com/todos')
    .then(response => {
        console.log(response)
        return response.json()
    })
    .then(json => console.log(json))
    .catch(error => console.log(error))
```

#### Вызов fetch внутри промиса.

```javascript
const getData = (url) =>
    new Promise((resolve, reject) => {
        fetch(url)
            .then(response => response.json())
            .then(json => resolve(json))
            .catch(error => reject(error))
    })

getData('https://jsonplaceholder.typicode.com/todos')
    .then(data => console.log(data))
    .catch(error => console.log(error.message))
```